### ISSUE TITLE
Reactivate

### ISSUE THREAD

**Issue by marcoongithubnow** [olajhidey/countdown_app#1]
What happens if the display goes to stand-by? How can the app reactivate?

**Comment by olajhidey** [comment]
You could pause the timer in the onPause(), onRestart(), onStop() lifecycle

**Comment by marcoongithubnow** [comment]
Ok, thanks. But my question was that a timer, for example of a minute, at the end must reactivate the display. Thanks again.

**Comment by olajhidey** [comment]
Yes it restart the display of the timer, after the timer is done and completed.

**Comment by marcoongithubnow** [comment]
Ok, thanks again, it works! But now I'm looking for an example to create a real timer, which can allow the display to stand by for several minutes, and then reopen the app. Do you know any examples?

**Comment by olajhidey** [comment]
Yes you could take a look at the android workmanager or scheduleTask https://developer.android.com/topic/libraries/architecture/workmanager/basics

Presently i dont have any example or project on it but workmanager or scheduleTask should do what youre looking for

**Comment by marcoongithubnow** [comment]
Thanks, i'm going to study workmanager !!!

**Comment by olajhidey** [comment]
alright cool
